#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RicardoDealCommunity.Droid.Resource", IsApplication=true)]

namespace RicardoDealCommunity.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::RicardoDealCommunity.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::RicardoDealCommunity.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::RicardoDealCommunity.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::RicardoDealCommunity.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int MvxDropDownItemTemplate = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int MvxGroupItemTemplate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int MvxLang = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int MvxTemplate = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int ic_create = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ic_deal = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int MvvmCrossTagId = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int MvxBindingTagUnique = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int CreateView = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int deal_template = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int HomeView = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ListView = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ProfileView = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int SplashScreen = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050004
			public const int Icon = 2131034116;
			
			// aapt resource value: 0x7F050000
			public const int ic_create = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_deal = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_home = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int ic_profile = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int hello = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010004 }
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771972};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F010006 }
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010002 }
			public static int[] MvxExpandableListView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010005 }
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010003 }
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771971};
			
			// aapt resource value: 0
			public const int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public const int MvxListView_MvxItemTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
